#!/usr/bin/env node

// =============================================================================
// SINGLE-FILE HTML COVERAGE REPORT GENERATOR
// =============================================================================
//
// Reads coverage-final.json (generated by Jest) and the original source files,
// then produces a single self-contained HTML file: coverage/coverage-report.html
//
// Features:
//   - Total coverage percentages (statements, branches, functions, lines)
//   - Per-file breakdown — click to expand
//   - Line-by-line source view — green (covered), red (not covered), gray (ignored)
//
// Usage: node scripts/coverage-report.js
//        (Automatically called by npm run test:coverage)
// =============================================================================

const fs = require('fs');
const path = require('path');

const coverageDir = path.join(__dirname, '..', 'coverage');
const jsonPath = path.join(coverageDir, 'coverage-final.json');
const outputPath = path.join(coverageDir, 'coverage-report.html');

if (!fs.existsSync(jsonPath)) {
  console.error('❌ coverage/coverage-final.json not found. Run tests with --coverage first.');
  process.exit(1);
}

const coverage = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));
const projectRoot = path.join(__dirname, '..');

// Calculate coverage stats for a file
function calcStats(fileCov) {
  const calc = (map) => {
    const entries = Object.values(map);
    if (entries.length === 0) return { covered: 0, total: 0, pct: 100 };
    let covered = 0;
    for (const val of entries) {
      if (typeof val === 'number') { if (val > 0) covered++; }
      else {
        // branch: array of counts
        for (const b of val) { if (b > 0) covered++; }
        return { covered, total: entries.reduce((s, v) => s + v.length, 0), pct: 0 };
      }
    }
    const total = entries.length;
    return { covered, total, pct: total === 0 ? 100 : Math.round(covered / total * 10000) / 100 };
  };

  // Branches need special handling
  const branchEntries = Object.values(fileCov.branchMap || {});
  let branchCovered = 0, branchTotal = 0;
  for (const key of Object.keys(fileCov.b || {})) {
    for (const count of fileCov.b[key]) {
      branchTotal++;
      if (count > 0) branchCovered++;
    }
  }

  const stmts = calc(fileCov.s);
  const fns = calc(fileCov.f);
  const stmtMap = fileCov.statementMap || {};
  const lineSet = new Set();
  const coveredLines = new Set();
  for (const [key, loc] of Object.entries(stmtMap)) {
    for (let l = loc.start.line; l <= loc.end.line; l++) {
      lineSet.add(l);
      if (fileCov.s[key] > 0) coveredLines.add(l);
    }
  }

  return {
    statements: stmts,
    branches: { covered: branchCovered, total: branchTotal, pct: branchTotal === 0 ? 100 : Math.round(branchCovered / branchTotal * 10000) / 100 },
    functions: fns,
    lines: { covered: coveredLines.size, total: lineSet.size, pct: lineSet.size === 0 ? 100 : Math.round(coveredLines.size / lineSet.size * 10000) / 100 },
    coveredLines,
    executableLines: lineSet,
  };
}

// Escape HTML entities
function esc(str) {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

// Color for percentage
function pctColor(pct) {
  if (pct >= 80) return '#3fb950';
  if (pct >= 50) return '#d29922';
  return '#f85149';
}

// Build per-file data
const files = [];
let totalStmts = { covered: 0, total: 0 };
let totalBranches = { covered: 0, total: 0 };
let totalFns = { covered: 0, total: 0 };
let totalLines = { covered: 0, total: 0 };

for (const [absPath, fileCov] of Object.entries(coverage)) {
  const relPath = path.relative(projectRoot, absPath);
  const stats = calcStats(fileCov);

  let source = '';
  try { source = fs.readFileSync(absPath, 'utf-8'); } catch (e) { source = '// Could not read source file'; }

  files.push({ relPath, stats, source });

  totalStmts.covered += stats.statements.covered;
  totalStmts.total += stats.statements.total;
  totalBranches.covered += stats.branches.covered;
  totalBranches.total += stats.branches.total;
  totalFns.covered += stats.functions.covered;
  totalFns.total += stats.functions.total;
  totalLines.covered += stats.lines.covered;
  totalLines.total += stats.lines.total;
}

const totalPct = (m) => m.total === 0 ? 100 : Math.round(m.covered / m.total * 10000) / 100;

// Build the source view for each file
function buildFileSource(file) {
  const lines = file.source.split('\n');
  let html = '';
  for (let i = 0; i < lines.length; i++) {
    const lineNum = i + 1;
    const isExecutable = file.stats.executableLines.has(lineNum);
    const isCovered = file.stats.coveredLines.has(lineNum);
    let bgColor = 'transparent';
    if (isExecutable) {
      bgColor = isCovered ? 'rgba(63,185,80,0.12)' : 'rgba(248,81,73,0.15)';
    }
    const marker = isExecutable ? (isCovered ? '✓' : '✗') : ' ';
    const markerColor = isExecutable ? (isCovered ? '#3fb950' : '#f85149') : 'transparent';
    html += `<div style="display:flex;background:${bgColor};min-height:22px;line-height:22px;">` +
      `<span style="min-width:48px;text-align:right;padding-right:12px;color:#484f58;user-select:none;font-size:12px;">${lineNum}</span>` +
      `<span style="min-width:18px;color:${markerColor};font-size:11px;user-select:none;">${marker}</span>` +
      `<span style="white-space:pre;tab-size:2;">${esc(lines[i])}</span></div>`;
  }
  return html;
}

// Generate HTML
const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Coverage Report</title>
<style>
  :root { --bg:#0d1117; --surface:#161b22; --border:#30363d; --text:#e6edf3; --muted:#8b949e; }
  * { margin:0; padding:0; box-sizing:border-box; }
  body { background:var(--bg); color:var(--text); font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif; padding:24px; }
  h1 { font-size:1.8em; margin-bottom:4px; }
  .sub { color:var(--muted); margin-bottom:24px; font-size:.9em; }
  .summary { display:flex; gap:16px; flex-wrap:wrap; margin-bottom:32px; }
  .stat-card { background:var(--surface); border:1px solid var(--border); border-radius:12px; padding:18px 24px; min-width:160px; flex:1; }
  .stat-label { color:var(--muted); font-size:.8em; text-transform:uppercase; letter-spacing:.5px; margin-bottom:4px; }
  .stat-pct { font-size:2em; font-weight:700; }
  .stat-detail { color:var(--muted); font-size:.8em; margin-top:2px; }
  .bar-bg { background:var(--bg); height:6px; border-radius:3px; margin-top:8px; overflow:hidden; }
  .bar-fill { height:100%; border-radius:3px; }
  .file-card { background:var(--surface); border:1px solid var(--border); border-radius:10px; margin-bottom:12px; overflow:hidden; }
  .file-header { padding:14px 18px; cursor:pointer; display:flex; justify-content:space-between; align-items:center; transition:background .2s; }
  .file-header:hover { background:rgba(88,166,255,.06); }
  .file-name { font-weight:600; font-size:.95em; }
  .file-stats { display:flex; gap:16px; font-size:.8em; color:var(--muted); }
  .file-stats span { white-space:nowrap; }
  .file-source { display:none; border-top:1px solid var(--border); padding:12px 0; font-family:'Fira Code',Consolas,monospace; font-size:13px; overflow-x:auto; background:#0d1117; }
  .file-source.open { display:block; }
  .arrow { transition:transform .2s; color:var(--muted); }
  .arrow.open { transform:rotate(90deg); }
  .legend { display:flex; gap:20px; margin-bottom:20px; color:var(--muted); font-size:.85em; }
  .legend-item { display:flex; align-items:center; gap:6px; }
  .legend-swatch { width:14px; height:14px; border-radius:3px; }
</style>
</head>
<body>
<h1>📊 Coverage Report</h1>
<p class="sub">Generated ${new Date().toISOString().replace('T', ' ').split('.')[0]} UTC · ${files.length} file${files.length !== 1 ? 's' : ''}</p>

<div class="summary">
  <div class="stat-card">
    <div class="stat-label">Statements</div>
    <div class="stat-pct" style="color:${pctColor(totalPct(totalStmts))}">${totalPct(totalStmts)}%</div>
    <div class="stat-detail">${totalStmts.covered} / ${totalStmts.total}</div>
    <div class="bar-bg"><div class="bar-fill" style="width:${totalPct(totalStmts)}%;background:${pctColor(totalPct(totalStmts))}"></div></div>
  </div>
  <div class="stat-card">
    <div class="stat-label">Branches</div>
    <div class="stat-pct" style="color:${pctColor(totalPct(totalBranches))}">${totalPct(totalBranches)}%</div>
    <div class="stat-detail">${totalBranches.covered} / ${totalBranches.total}</div>
    <div class="bar-bg"><div class="bar-fill" style="width:${totalPct(totalBranches)}%;background:${pctColor(totalPct(totalBranches))}"></div></div>
  </div>
  <div class="stat-card">
    <div class="stat-label">Functions</div>
    <div class="stat-pct" style="color:${pctColor(totalPct(totalFns))}">${totalPct(totalFns)}%</div>
    <div class="stat-detail">${totalFns.covered} / ${totalFns.total}</div>
    <div class="bar-bg"><div class="bar-fill" style="width:${totalPct(totalFns)}%;background:${pctColor(totalPct(totalFns))}"></div></div>
  </div>
  <div class="stat-card">
    <div class="stat-label">Lines</div>
    <div class="stat-pct" style="color:${pctColor(totalPct(totalLines))}">${totalPct(totalLines)}%</div>
    <div class="stat-detail">${totalLines.covered} / ${totalLines.total}</div>
    <div class="bar-bg"><div class="bar-fill" style="width:${totalPct(totalLines)}%;background:${pctColor(totalPct(totalLines))}"></div></div>
  </div>
</div>

<div class="legend">
  <div class="legend-item"><div class="legend-swatch" style="background:rgba(63,185,80,0.25)"></div> Covered</div>
  <div class="legend-item"><div class="legend-swatch" style="background:rgba(248,81,73,0.25)"></div> Not covered</div>
  <div class="legend-item"><div class="legend-swatch" style="background:transparent;border:1px solid var(--border)"></div> Not executable</div>
</div>

${files.map((f, i) => `<div class="file-card">
  <div class="file-header" onclick="toggle(${i})">
    <span class="file-name">${esc(f.relPath)}</span>
    <div style="display:flex;align-items:center;gap:16px;">
      <div class="file-stats">
        <span style="color:${pctColor(f.stats.statements.pct)}">Stmts ${f.stats.statements.pct}%</span>
        <span style="color:${pctColor(f.stats.branches.pct)}">Branch ${f.stats.branches.pct}%</span>
        <span style="color:${pctColor(f.stats.functions.pct)}">Funcs ${f.stats.functions.pct}%</span>
        <span style="color:${pctColor(f.stats.lines.pct)}">Lines ${f.stats.lines.pct}%</span>
      </div>
      <span class="arrow" id="arrow-${i}">▶</span>
    </div>
  </div>
  <div class="file-source" id="src-${i}">${buildFileSource(f)}</div>
</div>`).join('\n')}

<script>
function toggle(i) {
  const src = document.getElementById('src-' + i);
  const arrow = document.getElementById('arrow-' + i);
  src.classList.toggle('open');
  arrow.classList.toggle('open');
}
</script>
</body>
</html>`;

fs.writeFileSync(outputPath, html);
console.log(`\n📊 Coverage report: coverage/coverage-report.html`);
